name: CI/CD for Patient Risk App

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPO: patient-risk-app
  EC2_USER: ubuntu
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_KEY: ${{ secrets.EC2_KEY }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m py_compile app.py sagemakerendpoint.py

      - name: Deploy SageMaker Endpoint
        run: |
          echo "ðŸš€ Deploying SageMaker endpoint..."
          python train_model.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t $ECR_REPO .

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Push image to ECR
        run: |
          docker tag $ECR_REPO:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

      - name: Deploy Streamlit App to EC2
        run: |
          echo "Deploying new version to EC2..."
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem -r scripts/ $EC2_USER@$EC2_HOST:~/scripts
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
            export AWS_REGION=${{ env.AWS_REGION }}
            bash ~/scripts/stop_app.sh
            bash ~/scripts/start_app.sh
          EOF
      